fe = float(input("Foundation English Score:"))
gb = float(input("General Business Score:"))
ics = float(input("Introduction to Computer Systems Score:"))
cp = float(input("Computer Programming Score:"))
print("---Your Score---")
print("Foundation Engilsh :", fe)
print("General Business :", gb)
print("Introduction to Computer Systems :", ics)
print("Computer Programming :", cp)
